
version: '3.8'

services:
    api_gateway:
        container_name: api_gateway
        image: api-gateway:ft_transcendence
        build:
            context: .
            dockerfile: api-gateway/Dockerfile
        ports:
            - "80:80"
        # restart: always

        volumes:
            # - "/Volumes/EL\ MOUDDEN/Project/ft_transcendence/srcs/frontend/:/usr/share/nginx/html"
            - "/Users/ndahib/Desktop/basePage/srcs/frontend/:/usr/share/nginx/html"